name: Deploy to GCS using Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.6

    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/671902319686/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "terraformfinal@itsme-1234.iam.gserviceaccount.com"

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform apply -auto-approve

    - name: Dump OIDC token
      run: |
        echo "OIDC token URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
        echo "OIDC token: ${{ steps.auth.outputs.id_token }}"
